cafes = ['Não tente disfarçar seus erros com memes autodepreciativos.',
           'Nada parece impossível até voce tentar.',
           'Não se esqueça que ela já te esqueceu.',
           'Aprenda com seus erros. Continue Errando.',
           'Ainda dói.',
           'Você se humilha por pouco porque nunca espera muita coisa.',
           'Você cha,a de sonho pois sabe que é impossível.',
           'Só se arrepende quem tenta.',
           'Não deixe que um falso otimismo te de esperança.',
           'Hoje tem tudo pra ser diferente. Mas você não fará nada.',
           'O não e humilhação você ja tem. O que mais falta acontecer pra voce desistir.',
           'Invista naquilo que não tem futuro. Reclame quando tudo der errado.',
           'Desista antes do trauma.',
           'Pensar positivo não irá te livrar de realidade.',
           'Nunca é tarde para desistir no meio do caminho.',
           'Ela não está distante ela já partiu.',
           'Ou você supera ou você sofre.',
           'Ela sabe dos seus sentimentos. Mas não se importa.',
           'É tarde demais para pedir desculpas.',
           'Você espera pelo pior. E sempre recebe.',
           'Não desista até você ter magoado todos ao seu redor.',
           'Nada é tão ruim que você não consiga piorar.',
           'Quem desiste na hora certa perde a chance de se humilhar.',
           'A vida é mais do que sofrimento. Tem um pouco de frustração também.',
           'Quando você perceber já terá sido tarde demais.',
           'O Abraço dele foi mais confortável pra ela.',
           'Não desista no primeiro "não". Continue até ser bloqueado.',
           'Ninguém reconhece seus esforços porque você se esforça por pessoas erradas.',
           'Não deixe o arrependimento te impedir de errar novamente.',
           'Nunca perca a chance de deixar claro que você ainda não superou.',
           'Ela já esqueceu. Inclusive dos bons momentos.',
           'O amargo na sua boca é de arrependimento.',
           'Se olhe no espelho ao acordar. Chore logo pela manhã.',
           'Ele pensa sim em você. Mas só quando não está com quem ele ama.',
           'Ela sente sua falta. Quando precisa de alguém para se rebaixar por ela.',
           'Surpreenda as pessoas: Mostre que você é ainda pior do que pensaram.',
           'O seu melhor nem sempre é o suficiente.',
           'Seu ex ainda pensa em você. Quando lembra das piores escolhas da vida dele.',
           'Não deixe de insistir onde você sabe que não tem chance.',
           'Eles disseram que você não era capaz. Voce foi lá e mostrou que não era mesmo.',
           'Você tem chances até ela te conhecer direito.',
           'Se dedique o bastante para quando dar errado você ter certeza que a culpa é sua.',
           'Não deixe que o silêncio dela te impeça de seguir se humilhando e puxando assunto.',
           'O que eles chamam de isolmaneto, você chama de rotina.',
           'Não tem ninguém sentindo sua falta.',
           'Aproveite o isolamento e evite chorar em público.',
           'Tudo tem um lado positivo, até sua vida que é pura tragédia: aproveite o isolamento e chore em lugares da sua casa que você sequer imaginou.',
           'Você é grupo de reisco quando o assunto é ser trouxa.',
           'O isolamento te fez perceber que sua companhia é pessima.',
           'Lá fora não tem ninguém sentindo sua falta.',
           'Você não é tão importante. Mas seu isolamento é.',
           'O amor da sua vida está em quarentena com o amor da vida dela.',
           'Ninguém merece ficar em quarentena com você.',
           'Fique em casa de quarentena. Ninguém sentirá sua falta.',
           'Ela está de quarentena com outro.',
           'Pra quem já vive sozinho se isolar é apenas rotina.',
           'Seu passado te persegue porque você não o evita.',
           'Signo não é desculpa para o seu pouco talento.',
           'Pense que poderia ser pior. E talvez seja.',
           'Insista nos mesmos erros. Reclame que você errou.',
           'Enquanto você estiver no chão ninguém poderá te derrubar.',
           'Aproveite sua solidão você lutou muito para consegui-la.',
           'Você não tem personalidade forte. As pessoas apenas te acham insuportável.',
           'Seus erros do passado irão te perseguir no futuro.',
           'Diga que está tudo bem. Minta a si mesmo.',
           'Não desista ainda. Espere pela humilhação.',
           'Não deixe que sua falta de motivação de tentar. E errar.',
           'O problema não era você, era ele: Ele se encheu.',
           'Sua dor parece não ter fim. E não terá.',
           'Finais de semana são grandes oportunidadesde vê-la com outro.',
           'Ela já superou. Você ainda ensaia como pedir para voltar.',
           'Tente se lembrar dos bons momentos que vocês viveram juntos. Perceba que eles nunca existiram.',
           'O não você já tem. E vai continuar com ele.',
           'Se dedique o bastante para quando dar errado você ter certeza que a culpa é sua.',
           'Quem nem tenta nunca decepciona.',
           'Façam o que esperam de você: nada.',
           'Não deixe que o silêncio dela te impeça de seguir se humilhando e puxando assunto.',
           'Claro que ele lembra de você. Quando o assunto são pessoas insuportáveis.',
           'Compre aquilo que você não precisa para impressionar quem não se importa com você.',
           'Acredite em si mesmo e seja o primeiro a se decepcionar.',
           'Sonhe com ela enquanto ela se realiza com outro.',
           'Tente até desistir.',
           'O frio é ainda pior quando você se lembra que ela se aquece com outro.',
           'Porque deixar pra amanhã algo que você pode desistir hoje?',
           'Estar sempre triste evita que você fique na bad.',
           'Essa dor só irá embora quando você aceitar que ela não é mais sua.',
           'Estão demorando pra reconhecer seu talento porque talvez você não tenha nenhum.'
           ]
